---
- name: add aa new-model config
  hosts: ios
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: IOS config aaa new-model
      cisco.ios.ios_config:
        lines:
          - hostname {{ inventory_hostname }}
          - ntp server 1.1.1.1
      when: ansible_network_os == 'cisco.ios.ios'

      register: output1

    - debug:
         msg:
         - "{{ output1 }}"
