---
- name: gather some facts from a particular vyos machine
  hosts: vyos
  vars:
    subset: default

  tasks:

  - name: invoke vyos_facts with gather_subset=all
    vyos_facts:
      gather_subset: "{{ subset }}"

  - debug:
      msg:
      - "Host name:  {{ ansible_net_hostname }}"
      - "Model:  {{ ansible_net_model }}"
      - "Version:  {{ ansible_net_version }}"
      - "SerialNum:  {{ ansible_net_serialnum }}"
